services:
  db:
    image: mariadb:10.7
    command: '--default-authentication-plugin=mysql_native_password'
    volumes:
      - db_data:/var/lib/mysql
    restart: on-failure
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=wordpress
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
  wordpress:
    image: wordpress:6.7
    volumes:
      - './wp-content/mu-plugins:/var/www/html/wp-content/mu-plugins'
      - './wp-content/plugins:/var/www/html/wp-content/plugins'
      - './wp-content/themes:/var/www/html/wp-content/themes'
      - './wp-content/uploads:/var/www/html/wp-content/uploads'
      - './custom.php.ini:/usr/local/etc/php/conf.d/custom.php.ini'
    ports:
      - '8080:80'
    restart: on-failure
    environment:
      - WORDPRESS_DB_HOST=db
      - WORDPRESS_DB_USER=${DB_USER}
      - WORDPRESS_DB_PASSWORD=${DB_PASSWORD}
      - WORDPRESS_DB_NAME=wordpress
volumes:
  db_data:
