name: PHPCS
run-name: Checking PHP syntax with CodeSniffer
on: [push]
jobs:
  phpcs-linting:
    runs-on: ubuntu-latest
    steps:
      - name: Checking out
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2"
          tools: cs2pr, phpcs
      - name: Run PHPCS
        run: phpcs -q --extensions=php --report=checkstyle wp\-content
