on: pull_request

name: Inspections
jobs:
  runPHPCSInspection:
    name: Run PHPCS inspection
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0'
          coverage: none
          tools: composer
      - name: Composer install
        run: composer install --no-progress --no-interaction
        env:
          ACF_PRO_KEY: ${{ secrets.ACF_PRO_KEY }}
          ACF_VERSION: ${{ secrets.ACF_VERSION }}
      - name: Run PHPCS inspection
        uses: rtCamp/action-phpcs-code-review@v2
        env:
          GH_BOT_TOKEN: ${{ secrets.GH_BOT_TOKEN }}
          SKIP_FOLDERS: 'tests,.github'
          PHPCS_STANDARD_FILE_NAME: '.phpcs.xml'
          PHPCS_FILE_PATH: 'vendor/bin/phpcs'
        with:
          args: 'WordPress-VIP-Go'
