name: PHPCS
run-name: Checking PHP syntax with CodeSniffer
on: [push]
jobs:
  phpcs-linting:
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2"
          tools: cs2pr, phpcs
      - name: Get Composer cache directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"
      - name: Setup cache
        uses: pat-s/always-upload-cache@v1.1.4
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-
      - name: Install dependencies
        run: composer require --dev --prefer-dist --no-suggest --no-progress wp-coding-standards/wpcs:2.3.0
      - name: Run PHPCS
        run: phpcs -q --extensions=php --report=checkstyle wp-content/themes/
