on: pull_request
name: Inspections
jobs:
  runPHPCSInspection:
    name: Run PHPCS inspection
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      # Setup PHP with the required version and add extensions if needed any for composer install.
      # Ref: https://github.com/shivammathur/setup-php#heavy_plus_sign-php-extension-support
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0'
          coverage: none
          tools: composer

      # Install composer dependencies in the workflow run.
      - name: Composer install
        run: composer install --no-progress --no-interaction
        env:
          ACF_PRO_KEY: ${{ secrets.ACF_PRO_KEY }}
          ACF_VERSION: ${{ secrets.ACF_VERSION }}

      - name: Run PHPCS inspection
        uses: rtCamp/action-phpcs-code-review@master
        env:
          GH_BOT_TOKEN: ${{ secrets.GH_BOT_TOKEN }}
          SKIP_FOLDERS: 'vendor,.github'
