on:
  push:
  pull_request:

jobs:
  typescript-check:
    name: Typescript validity check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: install node v14
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: yarn install
        run: yarn install
      - name: tsc
        uses: icrawl/action-tsc@v1
